#!/bin/bash

export PATH="${PATH}:${HOME}/.config/bspwm/bin"


bspc config border_width	2
bspc config window_gap		10
# bspc config top_padding          30
# bspc config bottom_padding       10
# bspc config left_padding         10
# bspc config right_padding        10
bspc config split_ratio		0.50
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod4
bspc config automatic_scheme	spiral
bspc config borderless_monocle   true
bspc config gapless_monocle      false

Bspc config focused_border_color     "#26F0F1" #
bspc config normal_border_color      "#202A25" #

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
config borderless_monocle true

# Workspaces
#bspc monitor -d 1:  2:  3:  4:  5:  6:  7:  8:  9:
#bspc monitor -d                 
bspc monitor -d 1 2 3 4 5 6 7 8 9
#       

bspc rule -a firefox desktop=1
bspc rule -a Librewolf desktop=1
bspc rule -a brave-browser desktop=4
bspc rule -a Alacritty desktop=2
bspc rule -a kitty desktop=2
bspc rule -a nautilus desktop=2
bspc rule -a caja desktop=2
bspc rule -a ranger desktop=2
bspc rule -a okular desktop=3
bspc rule -a eog desktop=3
bspc rule -a onlyoffice desktop=3
bspc rule -a vlc desktop=4
bspc rule -a mpv desktop=4
bspc rule -a celluloid desktop=4
bspc rule -a spotify desktop=4
bspc rule -a telegram-desktop desktop=5
bspc rule -a whatsapp-for-linux desktop=5
bspc rule -a emacs desktop=6
bspc rule -a steam desktop=7
bspc rule -a supertuxkart desktop=7
bspc rule -a lutris desktop=7
bspc rule -a lxappearance desktop=8
bspc rule -a gnome-calculator state=floating follow=on
bspc rule -a nitrogen state=floating follow=on
bspc rule -a lxappearance state=floating follow=on
bspc rule -a zenity state=floating follow=on
bspc rule -a emacs state=tiled follow=on

xsetroot -cursor_name left_ptr
sxhkd &
notify-send " Welcome Back Sir" &
dunst --config ~/.config/dunst/dunstrc &
picom &
sh ~/.config/polybar/launch.sh &
#mate-panel &
xinput set-prop "ELAN0788:00 04F3:321A Touchpad" "libinput Tapping Enabled" 1 &
nitrogen --restore &
#/usr/bin/gnome-keyring-daemon --start --components=pkcs11 &
#/usr/libexec/mate-settings-daemon &
/usr/libexec/polkit-mate-authentication-agent-1 &
mpv --no-video ~/Music/startup.wav
mate-power-manager &
lxappearance --sync &
nm-applet &
copyq &
blueman-applet
bspfloat &

run() {
  if ! pgrep -f "$1" ;
  then
    "$@"&
  fi
}
#run "mate-session"
#run "mate-power-manager"
run "flameshot"
# run "nm-applet"
# run "copyq"

wmname LG3D
